name: backend branch test

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

permissions:
  contents: read
  
  
jobs:
  test:
    name: merge-test
    runs-on: ubuntu-latest
#     defaults:
#         run: 
#           working-directory: ./server
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: server/ ./gradlew build
      
